version: '3.8'

services:
  projeto:
    container_name: postgresql_duckdb
    image: postgres:16.0
    environment:
      POSTGRES_USER: unifor
      POSTGRES_PASSWORD: unifor
      POSTGRES_DB: unifor_duckdb
    ports:
      - "5437:5432"
    volumes:
    - ./src/sql:/docker-entrypoint-initdb.d