create table duckdb_ibge (
	COD_UF VARCHAR, 
	COD_MUN VARCHAR, 
	COD_ESPECIE VARCHAR, 
	LATITUDE VARCHAR, 
	LONGITUDE VARCHAR, 
	NV_GEO_COORD VARCHAR, 
	NOME_ARQUIVO VARCHAR, 
	DT_CADASTRO TIMESTAMP
)